modLoader = "javafml"
loaderVersion = "[47,)"
license = "MIT"

[[mods]]
modId = "tooltips_reforged_dyed"
version = "${version}"
displayName = "Tooltips Reforged Dyed"
authors = "yardenzamir"
description = '''
Custom user-defined tags for TooltipsReforged
'''

[[dependencies.tooltips_reforged_dyed]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.tooltips_reforged_dyed]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,1.20.5)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.tooltips_reforged_dyed]]
modId = "tooltips_reforged"
mandatory = true
versionRange = "[1.7,)"
ordering = "AFTER"
side = "CLIENT"
[mc-publish]
modrinth = "HI3AHY79"
curseforge = 1411209
loader = "forge"
mc_version = "1.20.1"
modrinth_slug = "tooltipsreforgeddyed"
curseforge_slug = "tooltipsreforgeddyed"
